Revert "adjust step sequence in pr-test-suite.yml"
This reverts commit 7404453fd72ac65dccc9fcc21cd6dcfcfebb64f5.

diff --git a/.github/workflows/pr-test-suite.yml b/.github/workflows/pr-test-suite.yml
--- a/.github/workflows/pr-test-suite.yml
+++ b/.github/workflows/pr-test-suite.yml
@@ -738,6 +738,12 @@ jobs:
         pushd ./tests/integration/iceberg/docker-compose/
         docker compose -f ./docker-compose.yml up -d
         popd
+    # Gravitino test setup
+    - name: Spin up Gravitino service
+      run: |
+        pushd ./tests/integration/gravitino/docker-compose/
+        docker compose -f ./docker-compose.yml up -d
+        popd
 
     # Unity tests
     - name: Run Unity integration tests (native)
@@ -798,22 +804,6 @@ jobs:
         python tools/aggregate_test_durations.py delta_lake_pytest_output.txt
       env:
         DAFT_RUNNER: ray
-
-    # Cleanup Iceberg docker services
-    - name: Cleanup Iceberg Docker services
-      if: always()
-      run: |
-        pushd ./tests/integration/iceberg/docker-compose/
-        docker compose -f ./docker-compose.yml down --volumes || true
-        popd
-
-    # Gravitino test setup
-    - name: Spin up Gravitino service
-      run: |
-        pushd ./tests/integration/gravitino/docker-compose/
-        docker compose -f ./docker-compose.yml up -d
-        popd
-
     # Gravitino tests
     - name: Run Gravitino integration tests (native)
       if: always()
@@ -838,11 +828,14 @@ jobs:
         GRAVITINO_ENDPOINT: http://127.0.0.1:8090
         GRAVITINO_METALAKE: metalake_demo
 
-    # Cleanup Gravitino docker services
-    - name: Cleanup Gravitino Docker services
+    # Cleanup docker services
+    - name: Cleanup Docker services
       if: always()
       run: |
         pushd ./tests/integration/gravitino/docker-compose/
+        docker compose -f ./docker-compose.yml down --volumes || true
+        popd
+        pushd ./tests/integration/iceberg/docker-compose/
         docker compose -f ./docker-compose.yml down --volumes || true
         popd
 
